version: "3"
services:
  leetcode-screenshot-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    cap_add:
      - SYS_ADMIN
    restart: always
    volumes:
      - ./image_cache:/home/pptruser/leetcode-screenshot/image_cache
